### PR TITLE
CORS module #15

### PR DESCRIPTION
**Pull request by Kinmarui**
I started working on this before there was PR https://github.com/spring-projects/spring-fu/pull/47 and solves (I hope) the same issue https://github.com/spring-projects/spring-fu/issues/15 but using DSL to allow user to define configuration
This is my first contribution so I would be thankful for any feedback

in test `context.beanDefinitionNames` is empty, is this expected behavior?

### CODE REVIEW

**Comment by Kinmarui** [comment]
Good point, I will try to get back to you in next 2 days (maybe even today but no guarantees).

**Comment by Kinmarui** [comment]
I'm working on it but maybe you will have better idea how to introduce varargs in this situaltion. Orginaly I passed `init: CorsConfiguration.() -> Unit` as function but `CorsConfiguration` doesn't have varargs support so should I 
1. inherit CorsConfiguration in my own class and add missing functions
2. create custom class w/o inheritance
3. other way?

**Comment by pivotal-issuemaster** [comment]
@Kinmarui Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-fu&pullRequestId=48) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Kinmarui Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-fu&pullRequestId=48)!

**Comment by sdeleuze** [comment]
You can use the [spread operator](https://kotlinlang.org/docs/reference/functions.html#variable-number-of-arguments-varargs) to convert `vararg` to list.

**Comment by Kinmarui** [comment]
My previous question was about how to expose to user that he can pass varargs and not how to use varargs. I decided to go with extensions functions for CorsConfiguration. Please let me know should I add extencions functions for all properties (i.e maxAge, allowCredentials)

also current implementation has limitation of setting defaults for all paths, but original API were more flexible and let it define per path. The only problem I have is that `"/api"(defaults=false) {}` looks atrocious but maybe I should still add support for it?

**Comment by sdeleuze** [comment]
The purpose of config DSL is to provide default autocomplete with minimal imports, so my proposal is to create a `CorsConfigurationDsl` that will natively expose the `vararg` methods and use internally a `CorsConfiguration`.

`"/api"(defaults=false) {}` is horrible I agree. Instead of that, I would provide a `defaults` setter in the DSL in order to be able to define `"/api" { defaults=false }`.

Could you please update the PR accordingly if you agree with these proposals?

**Comment by Kinmarui** [comment]
added `CorsConfigurationDsl` please check if this is what you had in mind

**Comment by sdeleuze** [comment]
Nice, we are almost ok now.

For `getConfiguration`, what about `class CorsConfigurationDsl : () -> CorsConfiguration` and implementing `invoke()` to return the Cors configuration ? I did like that in other places.

**Comment by Kinmarui** [comment]
updated accordingly

should I rebase all changes to one commit or add Java doc before this is ready to be merged?

**Comment by sdeleuze** [comment]
Yes please, if you can add [Kdoc](https://kotlinlang.org/docs/reference/kotlin-doc.html) that even better!

**Comment by sdeleuze** [comment]
@Kinmarui Hey, any chance you can do the last changes in order to allow me to merge this PR?

**Comment by sdeleuze** [comment]
Merged as 63bf4310dfbe132d92c7281aea31648be3e0673c, please contribute documentation as a separated PR if possible. Thanks for your contribution!

**Pull request closed without merging**
