### PR TITLE
Thymeleaf support

### PR DESCRIPTION
**Pull request by malltshik**
I'm not sure about need for this module, but still I've done it.
Thymeleaf engine support was implemented almost in the same way as mustache module.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Thanks for this PR, any chance you could explore how `spring.thymeleaf.*` [Spring Boot application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) could translate as Kotlin DSL?

**Comment by wilkinsona** [comment]
FWIW, I'm not sure that a DSL is the best way to apply that sort of configuration. You'd lose all of the benefits of externalised configuration for a start. Why not just use application.properties or application.yaml?

**Comment by malltshik** [comment]
Partly I agree with @wilkinsona 
But there still exist possibility to flexible configure your application over programmatic way.
This is kind of speciality of spring-fu (If I understood everything right)

I'll try to implement all of `sprint.thymeleaf.*` props a bit late

**Comment by wilkinsona** [comment]
Given Spring Fu's role as a playground for experimenting with ideas that can be fed into Spring Boot and Spring Framework, I'm not sure that it makes sense to spend time mapping (a subset of) Spring Boot's configuration properties to a programmatic DSL. Perhaps some experimentation in this area will prove me wrong, but it doesn't feel like something that's likely to make it into Boot or Framework.

**Comment by sdeleuze** [comment]
@wilkinsona I am not sure the programmatic DSL has to stop where application properties apply, I tend to think there will be and overlap between both. In some regards, this is a kind of unified configuration that is both declarative (like properties or yaml) and programmatic (like `@Configuration` + `@Bean`).

Compared to `application.properties` or `application.yaml`:
 * It provides a clever autocomplete out of the box where you can read easily default values (since it is part of the DSL API), optionally customize them and specify what is mandatory/optional
* It is more flexible (conditional configuration, dynamic values)
* It leverages the same format you are using for your application code while still being potentially externalized as a `.kts` file
* I have seen regularly users complaining about yaml being fragile and properties too limited

To me this is a different way of writing the configuration like Maven and Gradle build files are different. I don't say it is better or worth, it is different and IMO worth to explore because conceptually it seems to me this could be used to configure Boot configurations. Of course, it is quite early to say and this will be decided by Boot team but I don't think it is a waste of time.

What I am mostly interested in @malltshik is the DSL side in order to have more non trivial example to get a better idea. The implementation should leverage Boot configuration asap to avoid accumulating too much configuration stuff on Spring Fu side, I will reach you tomorrow about that.

**Comment by malltshik** [comment]
Should DSL looks like: 
```kotlin
    thymeleaf {
        cache(true)
        suffix(".custom")
        prefix("classpath:/views/")
    }
```
I did couple methods, however I'm not sure about correctness of their implementation.
@sdeleuze could you look at the last commit and tell me what's wrong with it? What would be better to do?

**Comment by sdeleuze** [comment]
@malltshik What about using names optional parameters with default values instead? That would ensure they are specified a single time and would provide some hints about default values to the user.

**Comment by malltshik** [comment]
@sdeleuze do u mean something like that:
```kotlin
thymeleaf(cache=true, suffix=".xhtml", prefix="classpath:/folder/")
```
All thymeleaf properties as named arguments in one method?

**Comment by sdeleuze** [comment]
Yes, with named parameters and optional ones with default value that seems a way to explore IMO.

**Comment by sdeleuze** [comment]
Merged as https://github.com/spring-projects/spring-fu/commit/e52f181d853dadeac87d74b0331addd04b99ca84, thanks. Feel free to add support for other properties if you can via another PR.

**Comment by malltshik** [comment]
I’ll do my best in free time. 
Thanks.

**Pull request closed without merging**
